services:
  postgres:
    image: postgres:18-alpine
    container_name: vocab_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vocab_ai
      # optional but explicit:
      PGDATA: /var/lib/postgresql/18/docker
    ports:
      - "5432:5432"
    volumes:
      - pg18_data:/var/lib/postgresql/18/docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d vocab_ai || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg18_data:
    driver: local